import { Header, Footer } from '.'
import Head from 'next/head'


// this component call from 🟨🟨🟨 ../pages/_app.js 🟨🟨🟨 file...
const Layout = ({ children }) => {

    return (
        <>
            <Head>
                <title>Blog</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/blog.ico" />
            </Head>


            <Header />

            <main>
                {
                    children
                }
            </main>

            <Footer />
        </>
    )
}

export default Layout